### ISSUE TITLE
Doony hides last build from history

### ISSUE THREAD

**Issue by syphernl** [kevinburke/doony#80]
Due to this piece of CSS in Doony:

```
#buildHistory .build-row:last-child {
display: none;
}
```

The last entry of the build history is hidden because of this, which means build 1 for each new job created.

**Comment by aehlke** [comment]
Is this still true? Seems like a minor thing to fix, but it would be a deal breaker for me...

**Comment by elatt** [comment]
I still see it in the latest git pull and Jenkins LTS release
